// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTokens() {
  return window['go']['drawer']['Api']['ClearTokens']();
}

export function GetPixel(arg1, arg2) {
  return window['go']['drawer']['Api']['GetPixel'](arg1, arg2);
}

export function GetToken(arg1, arg2) {
  return window['go']['drawer']['Api']['GetToken'](arg1, arg2);
}

export function GetTokenOrEmpty(arg1, arg2) {
  return window['go']['drawer']['Api']['GetTokenOrEmpty'](arg1, arg2);
}

export function ReadToken() {
  return window['go']['drawer']['Api']['ReadToken']();
}

export function SaveBoard(arg1) {
  return window['go']['drawer']['Api']['SaveBoard'](arg1);
}

export function SaveToken() {
  return window['go']['drawer']['Api']['SaveToken']();
}

export function SetPixel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['drawer']['Api']['SetPixel'](arg1, arg2, arg3, arg4, arg5);
}

export function Update() {
  return window['go']['drawer']['Api']['Update']();
}
