// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {io} from '../models';

export function GetPixel(arg1:number,arg2:number):Promise<number>;

export function GetToken(arg1:number,arg2:string):Promise<boolean|string>;

export function GetTokenOrEmpty(arg1:number,arg2:string):Promise<string>;

export function ReadToken():Promise<void>;

export function SaveBoard(arg1:io.Writer):Promise<void>;

export function SaveToken():Promise<void>;

export function SetPixel(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<boolean>;

export function Update():Promise<void>;
