// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToken(arg1:number,arg2:string):Promise<void>;

export function GetPixel(arg1:number,arg2:number):Promise<number>;

export function GetTokens():Promise<{[key: number]: string}>;

export function ImageSize():Promise<number|number>;

export function Reset():Promise<void>;

export function SetImage(arg1:string):Promise<void>;

export function Start():Promise<void>;
