// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToken(arg1, arg2) {
  return window['go']['drawer']['ImageDrawer']['AddToken'](arg1, arg2);
}

export function GetPixel(arg1, arg2) {
  return window['go']['drawer']['ImageDrawer']['GetPixel'](arg1, arg2);
}

export function GetTokens() {
  return window['go']['drawer']['ImageDrawer']['GetTokens']();
}

export function ImageSize() {
  return window['go']['drawer']['ImageDrawer']['ImageSize']();
}

export function Reset() {
  return window['go']['drawer']['ImageDrawer']['Reset']();
}

export function SetImage(arg1) {
  return window['go']['drawer']['ImageDrawer']['SetImage'](arg1);
}

export function Start() {
  return window['go']['drawer']['ImageDrawer']['Start']();
}
