// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FromBase64(arg1) {
  return window['go']['main']['ImgBase64']['FromBase64'](arg1);
}

export function GetBoard() {
  return window['go']['main']['ImgBase64']['GetBoard']();
}
